# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180130_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='histroy',
            name='patch_type',
            field=models.CharField(db_column='c_patch_type', default='', help_text='all全部, percentage:10按百分比10, kwarg:k=v按参数k=v', max_length=64, verbose_name='补丁类型'),
        ),
    ]
