# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-02 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_histroy_patch_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patch',
            name='app_channel',
        ),
        migrations.AlterField(
            model_name='patchmonitoring',
            name='app_packname',
            field=models.CharField(blank=True, db_column='c_app_pack_name', max_length=255, null=True, verbose_name='APP包名'),
        ),
    ]
